replicaCount: 2

image:
  repository: sameerroboshopacr.azurecr.io/payment
  tag: v1
  pullPolicy: IfNotPresent

service:
  port: 8080

env:
  CART_HOST: cart
  CART_PORT: "8080"

  USER_HOST: user
  USER_PORT: "8080"

  PAYMENT_GATEWAY: https://google.com/

  AMQP_HOST: rabbitmq
  AMQP_USER: roboshop
  AMQP_PASS: roboshop123

resources: {}