apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: rabbitmq-secret
  namespace: roboshop

  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:

  refreshInterval: 1h

  secretStoreRef:
    name: azure-keyvault
    kind: SecretStore

  target:
    name: rabbitmq-secret

  data:

  - secretKey: username
    remoteRef:
      key: rabbitmq-username

  - secretKey: rabbitmq-password

    remoteRef:
      key: rabbitmq-password