apiVersion: external-secrets.io/v1
kind: SecretStore

metadata:
  name: azure-keyvault
  namespace: roboshop
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  provider:

    azurekv:

      tenantId: {{ .Values.tenantId }}

      vaultUrl: https://{{ .Values.keyVaultName }}.vault.azure.net

      authType: WorkloadIdentity

      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets