apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mongodb
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  serviceName: mongodb-headless

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
      - name: mongodb

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: 27017

        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 20
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 60
          periodSeconds: 20

        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db

  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage

    spec:
      storageClassName: managed-csi

      accessModes:
      - ReadWriteOnce

      resources:
        requests:
          storage: {{ .Values.storage.size }}