apiVersion: apps/v1
kind: Deployment

metadata:
  name: shipping
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: shipping

  template:

    metadata:
      labels:
        app: shipping

    spec:

      containers:

      - name: shipping

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: 8080

        env:

        - name: DB_HOST
          value: "{{ .Values.env.DB_HOST }}"

        - name: CART_ENDPOINT
          value: "{{ .Values.env.CART_ENDPOINT }}"

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5