apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: roboshop-applications
  namespace: argocd

spec:
  generators:
  - list:
      elements:

      - app: external-secrets
        namespace: external-secrets

      - app: external-secrets-config
        namespace: roboshop

      - app: metrics-server
        namespace: kube-system

      - app: mongodb
        namespace: roboshop
      - app: mysql
        namespace: roboshop
      - app: redis
        namespace: roboshop
      - app: rabbitmq
        namespace: roboshop

      - app: catalogue-schema
        namespace: roboshop
      - app: shipping-schema
        namespace: roboshop

      - app: catalogue
        namespace: roboshop
      - app: user
        namespace: roboshop
      - app: cart
        namespace: roboshop
      - app: shipping
        namespace: roboshop
      - app: payment
        namespace: roboshop
      - app: frontend
        namespace: roboshop
      - app: hpa
        namespace: roboshop

      - app: toolbox
        namespace: roboshop

      - app: roboshop-ingress
        namespace: roboshop

  template:

    metadata:
      name: "{{app}}"

    spec:

      project: default

      source:
        repoURL: https://github.com/Sameer-Sarrainodu/ecommerce-gitops.git
        targetRevision: HEAD
        path: helm/{{app}}

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
        - CreateNamespace=true