apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ingress-nginx
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.0

    helm:
      values: |
        controller:
          replicaCount: 2
          service:
            annotations:
              # Fixes Port 80 health probes by pointing to Nginx's internal check route
              service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
              # Fixes Port 443 by ensuring Azure uses a plain TCP connection check instead of HTTP
              service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probes: "2"

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
    - CreateNamespace=true