apiVersion: batch/v1
kind: Job
metadata:
  name: catalogue-schema
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: catalogue-schema
        image: sameerroboshopacr.azurecr.io/catalogue-schema:v1
        command:
        - sh
        - -c
        - |
          echo "Checking connection to MongoDB..."
          until mongosh --host mongodb --eval "db.adminCommand('ping')" >/dev/null 2>&1
          do
            echo "Waiting for mongodb to be fully ready..."
            sleep 5
          done

          echo "MongoDB is ready! Running schema initialization..."
          
          # Fixed connection string syntax
          mongosh "mongodb://mongodb/catalogue" /init.js
          mongosh "mongodb://mongodb/catalogue" /master-data.js

          echo "Catalogue schema migration completed successfully."