apiVersion: batch/v1
kind: Job

metadata:
  name: catalogue-schema
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded

spec:

  template:

    spec:

      restartPolicy: Never

      containers:

      - name: schema-loader

        image: mongo:7.0

        command:
        - sh
        - -c
        - |
          mongosh mongodb/catalogue /schema/master-data.js

        volumeMounts:

        - name: schema
          mountPath: /schema

      volumes:

      - name: schema

        configMap:
          name: catalogue-schema