apiVersion: batch/v1
kind: Job

metadata:
  name: catalogue-schema

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:

  backoffLimit: 1

  ttlSecondsAfterFinished: 300

  activeDeadlineSeconds: 600

  template:

    spec:

      restartPolicy: Never

      containers:

      - name: catalogue-schema

        image: sameerroboshopacr.azurecr.io/catalogue-schema:v1

        command:
        - sh
        - -c
        - |
          set -e

          echo "Waiting for MongoDB..."

          until nc -z mongodb 27017
          do
            sleep 5
          done

          echo "Loading init.js"

          mongosh mongodb://mongodb:27017/catalogue /init.js

          echo "Loading master-data.js"

          mongosh mongodb://mongodb:27017/catalogue /master-data.js

          echo "Catalogue schema completed successfully"