apiVersion: batch/v1
kind: Job

metadata:
  name: shipping-schema

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:

  backoffLimit: 1

  template:

    spec:

      restartPolicy: Never

      containers:

      - name: shipping-schema

        image: sameerroboshopacr.azurecr.io/shipping-schema:v1

        env:

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password

        command:
        - sh
        - -c
        - |
          until nc -z mysql 3306
          do
            echo "waiting for mysql"
            sleep 5
          done

          mysql \
            -h mysql \
            -uroot \
            -p${MYSQL_ROOT_PASSWORD} \
            < /schema.sql

          mysql \
            -h mysql \
            -uroot \
            -p${MYSQL_ROOT_PASSWORD} \
            < /app-user.sql

          mysql \
            -h mysql \
            -uroot \
            -p${MYSQL_ROOT_PASSWORD} \
            cities \
            < /master-data.sql