external-secrets:

  installCRDs: true

  serviceAccount:
    create: true
    name: external-secrets

    annotations:
      azure.workload.identity/client-id: "fce55892-3d72-4242-82b9-5ad5805753a4"

  podLabels:
    azure.workload.identity/use: "true"

  nodeSelector: {}

  tolerations: []